spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/teitter?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://localhost:3306/teitterplusp?characterEncoding=utf-8&useSSL=true
    username: root
    password: 821552
  servlet:
    multipart:
      max-file-size: 5MB
  main:
    allow-circular-references: true
  jackson:
    default-property-inclusion: non_empty #全局控制，过滤掉传给前端的null和空值
  redis:
    host: 117.78.0.131
    port: 6379
    password: 821552
#  jackson:
#    date-format: yyyyMMdd
#    time-zone: GMT+8

mybatis-plus:
  type-aliases-package: com.twitter.twitterplusp.bean
  configuration:
    use-generated-keys: true
server:
#  servlet:
#    session:
#      cookie:
#        same-site: none
#        max-age: 3600
#        secure: true
#        http-only: false
  port: 8090
#  ssl:
#    key-store-password: 4q57gk132f237r
#    key-store-type: JKS
#    key-store: classpath:heron.love.jks
#    enabled: true

######### 自定义 ##########
teitter:
  images:
    path: /images/tweetFile

user:
  avatar:
    path: /images/avatarFile
