spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/twitter?characterEncoding=utf-8&useSSL=false
    username: root
    password: 821552
  servlet:
    multipart:
      max-file-size: 5MB
#  jackson:
#    date-format: yyyyMMdd
#    time-zone: GMT+8

mybatis-plus:
  type-aliases-package: com.twitter.twitterplus.bean
server:
  servlet:
    session:
      cookie:
        same-site: none
        max-age: 3600
        secure: true
        http-only: false
  port: 8090
  ssl:
    key-store-password: 4q57gk132f237r
    key-store-type: JKS
    key-store: classpath:heron.love.jks
    enabled: true
