spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3307/teitter?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://localhost:3307/teitterold?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://117.78.0.131:3306/teitterplusp?characterEncoding=utf-8&useSSL=true
    url: jdbc:mysql://47.99.155.86:3306/twitter?characterEncoding=utf-8&useSSL=false
    username: Glu
    password: Gl821552133
  main:
    allow-circular-references: true
  jackson:
    default-property-inclusion: non_empty #全局控制，过滤掉传给前端的null和空值
  redis:
    host: 47.99.155.86
    port: 6379
    password: Gl821552133
  servlet:
    multipart:
      max-file-size: 20MB
      enabled: true
      max-request-size: 1000MB
#  jackson:
#    date-format: yyyyMMdd
#    time-zone: GMT+8

mybatis-plus:
  type-aliases-package: com.twitter.twitterplusp.bean
  configuration:
    use-generated-keys: true
server:
  servlet:
    session:
      cookie:
        same-site: none
        max-age: 3600
        secure: true
        http-only: false
  port: 8070
#  port: 8090
#  ssl:
#    key-store:  classpath:teitter.soul87.top.jks
#    key-store-password: 31un3zoq
#    key-store-type: JKS
#    enabled: true
#  ssl:
#    key-store-password: 4q57gk132f237r
#    key-store-type: JKS
#    key-store: classpath:heron.love.jks
#    enabled: true
  ssl:
    key-store-password: pmcqnfmi
    key-store-type: JKS
    key-store: classpath:teitter.heron.ltd.jks
    enabled: true

######### 自定义 ##########

images:
  path: /teitterFile/images/

videos:
  path: /teitterFile/videos/

  resources:
    static-locations: classpath:/templates/
logging:
  level:
    com.twitter.twitterplusp: debug

